version: '3.9'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - src/.env
    hostname: "postgres"

  backend:
    build:
      context: src/
      dockerfile: Backend.dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - src/.env

  redis:
    image: redis:7-alpine
    volumes:
      - redis_db:/data

  celery:
    build:
      context: src/
      dockerfile: Celery.dockerfile
    depends_on:
      - backend
      - redis
    env_file:
      - src/.env

volumes:
  postgres_db:
  redis_db: